<table class="no_border_table" style="width:952px;" cellpadding="0" cellspacing="0">
  <tbody>
<tr>
  <td height="38px">&nbsp;</td>
</tr>
<td class="table_header"><span class="table_span"><em><strong>BLOG</strong></em></span></td>
</tr>
  </tbody>
</table>
<table class="no_border_table" style="width: 952px;">
<tbody>
<tr>
<td style="width: 90%; font-size: 12px; padding-top: 32px; " rowspan="5">
<!-- <div class="page-title blog-title <?php if (!$this->isFirstPage()): ?>not-<?php endif; ?>first-page<?php if ($this->isFirstPage() && $this->getTagLine()): ?> with-tagline<?php endif; ?>">
	<h1><?php echo $this->escapeHtml($this->getBlogTitle()) ?></h1>
</div> -->
<?php if ($this->isFirstPage() && $this->getTagLine()): ?>
	<!-- <p class="blog-desc blog-tag-line"><?php echo $this->escapeHtml($this->getTagLine()) ?></p> -->
<?php endif; ?>
<div class="blog-home">
	<?php echo $this->getPostListHtml() ?>
</div>
</td>
<td rowspan="5" bgcolor="#000000"><!--nothing--></td>
<td style="width: 10%; height: 155px; padding-left: 14px;"><p><span style="font-size: medium;"><strong><br />
</strong></span></p>
  <?php echo Mage::getSingleton('core/layout')
      ->createBlock('wordpress/sidebar_widget_categories')
      ->setTemplate('wordpress/sidebar/widget/categories.phtml')
      ->toHtml() ?>
</tr>
<tr>
<td height="1" bgcolor="#000000"><!--nothing--></td>
</tr>
<tr>
<td style="height: 90px; padding-left: 14px;"><p><strong><br />
  </strong></p>
  <?php echo Mage::getSingleton('core/layout')
        ->createBlock('wordpress/sidebar_widget_archives')
        ->setTemplate('wordpress/sidebar/widget/archives.phtml')
        ->toHtml() ?>
</tr>
</tbody>
</table>