<?php
$link =  "//$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$escaped_link = htmlspecialchars($link, ENT_QUOTES, 'UTF-8');

$breadcrumb = str_replace(".html", "",$escaped_link);
$breadcrumb = str_replace("//www.pursuitbicycles.com", "",$breadcrumb);
$breadcrumb = strtoupper($breadcrumb);
if(strrpos($breadcrumb, "/CATALOGSEARCH/RESULT/?Q=") === false) {
 	$breadcrumbArray = split("/", $breadcrumb);
    array_splice($breadcrumbArray, 0, 1);
    $bannerName = "banner_".strtolower($breadcrumbArray[1]);
    $bannerName = str_replace("-", "",$bannerName);

    $breadcrumbArray[0] = "<a class='white_red' href='https://www.pursuitbicycles.com/shop.html'>".$breadcrumbArray[0]."</a>";
    $breadcrumbArray[1] = "<a class='white_red' href='../".strtolower($breadcrumbArray[1]).".html'>".$breadcrumbArray[1]."</a>";
    $breadcrumb = "/ ".$breadcrumbArray[0]." / ".$breadcrumbArray[1]." / ".$breadcrumbArray[2];

    //remove sort order from breadcrumb
    $breadcrumbArray = split("\?SORT=", $breadcrumb);
    $currentSort = "name";
    if($breadcrumbArray[1]) {
    	$currentSort = strtolower($breadcrumbArray[1]);
    }

    $breadcrumb = $breadcrumbArray[0];
}else {
	$breadcrumb = str_replace("/CATALOGSEARCH/RESULT/?Q=", "",$breadcrumb);
	$breadcrumbArray = split("&AMP;SORT=", $breadcrumb);
	$breadcrumb = "/ <a class='white_red' href='https://www.pursuitbicycles.com/shop.html'>shop</a>"." / ".$breadcrumbArray[0];
}
?>
<?php
	$_productCollection=$this->getLoadedProductCollection();
	$_helper = $this->helper('catalog/output'); ?>
<?php if(!$_productCollection->count()): ?>
	<p><br><br><br><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<?php
	    function sort_by_key($records, $field, $reverse=false)
        {
            $hash = array();

            if($field == "size") {
            	$sizeCount=100;
            	foreach($records as $record)
				{
					$size = Mage::getResourceModel('catalog/product')->getAttributeRawValue($record->getId(), 'size', 1);

					if($size) {
						if(!$hash[$size]) {
							$hash[$size] = $record;
						}else {
							$aText = "a";
							while($hash[$size.$aText]) {
								$aText = $aText."a";
							}

							$hash[$size.$aText] = $record;
						}
					}else {
						$hash[$sizeCount++] = $record;
					}
				}
            }else {
            	foreach($records as $record)
				{
					if(!$hash[$record[$field]]) {
						$hash[$record[$field]] = $record;
					}else {
						$aText = "a";
						while($hash[$record[$field].$aText]) {
							$aText = $aText."a";
						}

						$hash[$record[$field].$aText] = $record;
					}
				}
            }

            ($reverse)? krsort($hash) : ksort($hash);

            $records = array();

            foreach($hash as $record)
            {
                $records []= $record;
            }

            return $records;
        }

		$_mainCat = Mage::getModel('catalog/category')->load(Mage::getModel('catalog/layer')->getCurrentCategory()->getId());
		$_mainChildrenCats = $_mainCat->getAllChildren(true);
		$_sortedProductsCollection = array();
		$_isCollectionPage = true;
		$_isSearch = false;

		//Separate products by category
		if(substr_count($_SERVER['REQUEST_URI'], "/") > 2) {
			$mainName = $this->getLayer()->getCurrentCategory()->getName();
			if($mainName == "LIGHTSPEED_ROOT_CATEGORY") {
				$mainName = str_replace("//www.pursuitbicycles.com/catalogsearch/result/?q=","",$escaped_link);
				$_isSearch = true;
			}
			$mainName = str_replace(" ","+",$mainName);
			$_sortedProductsCollection[$mainName] = array();

			foreach ($_productCollection as $_product) {
				array_push($_sortedProductsCollection[$mainName], $_product);
			}

			$_isCollectionPage = false;

			switch($currentSort) {
				case "name":
					$_sortedProductsCollection[$mainName] = sort_by_key($_sortedProductsCollection[$mainName], "name");
					break;
				case "highestprice":
					$_sortedProductsCollection[$mainName] = sort_by_key($_sortedProductsCollection[$mainName], "price", true);
					break;
				case "lowestprice":
					$_sortedProductsCollection[$mainName] = sort_by_key($_sortedProductsCollection[$mainName], "price");
                	break;
				case "newest":
					$_sortedProductsCollection[$mainName] = sort_by_key($_sortedProductsCollection[$mainName], "created_at");
					break;
				case "size":
					$_sortedProductsCollection[$mainName] = sort_by_key($_sortedProductsCollection[$mainName], "size");
					break;
				default:
					break;
			}
		}else {
			$productPositions = array();
			foreach ($_productCollection as $_product) {
				$cats = $_product->getCategoryIds();
				foreach ($cats as $category_id) {
					$_cat = Mage::getModel('catalog/category')->load($category_id) ;
					$productPositions[$_cat->getName()] = $_cat->getProductsPosition();

					if(in_array($category_id, $_mainChildrenCats) && $category_id != $_mainCat->getId()) {
						if(!$_sortedProductsCollection[$_cat->getName()]) {
							$_sortedProductsCollection[$_cat->getName()] = array();
						}

						if(count($_sortedProductsCollection[$_cat->getName()]) < 4) {
							array_push($_sortedProductsCollection[$_cat->getName()], $_product);
						}else {
							$breakIndex = -1;
							$lastPos = 0;
							foreach($_sortedProductsCollection[$_cat->getName()] as $catProduct) {
								if($productPositions[$_cat->getName()][$_product->getId()] < $productPositions[$_cat->getName()][$catProduct->getId()]) {
									if($lastPos < $productPositions[$_cat->getName()][$catProduct->getId()]) {
										$breakIndex = array_search($catProduct, $_sortedProductsCollection[$_cat->getName()]);
									}
									$lastPos = $productPositions[$_cat->getName()][$catProduct->getId()];
								}
							}

							if($breakIndex != -1) {
                                $_sortedProductsCollection[$_cat->getName()][$breakIndex] = $_product;
							}
						}
					}
				}
			}

			foreach ($_sortedProductsCollection as $key => $_sortedProductArray) {
				$sorted=false;
				$productIndex=1;
				if(count($_sortedProductArray) > 1) {
					while(!$sorted) {
						for($productIndex=1; $productIndex < count($_sortedProductArray); $productIndex++) {
							$product1 = $_sortedProductsCollection[$key][$productIndex - 1];
							$product2 = $_sortedProductsCollection[$key][$productIndex];

							if($product1 && $product2) {
								if($productPositions[$key][$product2->getId()] < $productPositions[$key][$product1->getId()]) {
									$_sortedProductsCollection[$key][$productIndex - 1] = $product2;
									$_sortedProductsCollection[$key][$productIndex] = $product1;
									break;
								}
							}
						}
						if($productIndex > (count($_sortedProductArray)-1)) {
							$sorted = true;
						}
					}
				}
			}
		}

		$subCats = array();
        $children = Mage::getModel('catalog/category')->getCategories($_mainCat->getId(), 1, true, false);
        foreach ($children as $category)
        {
            $subCats[$category->getPosition()] = $category->getId();
        }

        if($mainName) {
        	$subCats[0] = $_mainCat->getId();
        }

        if($_isSearch) {
			$subCats = array();
        }
	?>
<?php if($_isCollectionPage): ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($bannerName)->toHtml(); ?>
<?php endif; ?>
<?php for($subCatIndex=0; $subCatIndex < count($subCats) + 1; $subCatIndex++): ?>
	<? $_cat = Mage::getModel('catalog/category')->load($subCats[$subCatIndex]); ?>
	<? $name = $_cat->getName(); ?>
	<?php if($_isSearch) {
			$catName = $mainName;
		}else {
			$catName = $_cat->getName();
		} ?>
	<?php $_sortedProductArray = $_sortedProductsCollection[$catName]; ?>
	<?php if(is_array($_sortedProductArray)): ?>
	<table class="no_border_table" style="width:952px;" cellpadding="0" cellspacing="0">
	  <tbody>
		<tr>
			<td height="42px">&nbsp;</td>
		</tr>
		<tr>
			<td class="table_header">
			<div class="table_span">
			<?php if($_isCollectionPage): ?>
			<?php echo $name; ?>
			</div>
			<div class="table_span" style="
				float: right;
				padding-right: 15px;
			"><a class="white_red" href="<?php echo str_replace(".html", "", $escaped_link)."/".strtolower($name).".html"; ?>">View All</a></span>
			<?php else: ?>
			<div style="float: left; padding-top: 14px;">
			<?php echo $breadcrumb; ?>
			</div>
			<select id="sortSelect" class="cs-select cs-skin-border">
				<option value="" disabled selected>Sort By</option>
				<option value="newest">Newest</option>
				<option value="name">Name</option>
				<option value="size">Size</option>
				<option value="lowestprice">Lowest Price</option>
				<option value="highestprice">Highest Price</option>
			</select>
			</div>
			<?php endif; ?>
			</td>
		</tr>
	  </tbody>
	</table>
	<table class="no_border_table" style="width: 952px;">
	<tbody>
	<tr>
	  <td style="width: 100%; font-size: 12px;">
		<table style="width: 100%;">
			<tbody>
			<tr>
				<td>
				<div class="category-products">
					<?php // List mode ?>
					<?php if(0): ?> <!-- if($this->getMode()!='grid') never set 'list' mode -->
					<ol class="products-list" id="products-list">
					<?php for ($prodIndex =0; $prodIndex < sizeof($_sortedProductArray); $prodIndex++): ?>
						<?php $_product = $_sortedProductArray[$prodIndex] ?>
						<li class="item<?php if( $prodIndex == sizeof($_sortedProductArray) ): ?> last<?php endif; ?>">
							<?php // Product Image ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(226); ?>" width="226" height="226" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							<?php // Product description ?>
							<div class="product-shop">
								<div class="f-fix">
									<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
									<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
									<?php if($_product->getRatingSummary()): ?>
									<?php echo $this->getReviewsSummaryHtml($_product) ?>
									<?php endif; ?>
									<?php echo $this->getPriceHtml($_product, true) ?>
									<?php if($_product->isSaleable()): ?>
										<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									<div class="desc std">
										<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
									</div>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
						</li>
					<?php endfor; ?>
					</ol>
					<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

					<?php else: ?>

					<?php // Grid Mode ?>

					<?php $_collectionSize = count($_sortedProductArray) ?>
					<?php $_columnCount = $this->getColumnCount(); ?>
					<?php $i = 0 ?>
					<?php for ($prodIndex =0; $prodIndex < count($_sortedProductArray); $prodIndex++): ?>
						<?php $_product = $_sortedProductArray[$prodIndex] ?>
						<?php if ($i++%$_columnCount==0): ?>
						<ul class="products-grid">
						<?php endif ?>
							<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(238); ?>" width="238" height="238" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
								<?php if($_product->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php endif; ?>
								<?php
									$priceHtml = $this->getPriceHtml($_product, true);
									echo str_replace("<span class=\"price\">","<span class=\"price\">price: ", $priceHtml);
								?>
								<!-- //Remove Add to Cart In Thumbnails
								<div class="actions">
									<?php if($_product->isSaleable()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="red_add_button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php if(0): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
									</ul>
								</div>
								-->
							</li>
						<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
						</ul>
						<?php endif ?>
						<?php endfor ?>
						<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
					<?php endif; ?>

					<!--<div class="toolbar-bottom">
						<?php echo $this->getToolbarHtml() ?>
					</div>-->
				</div>
				</td>
			</tr>
			</tbody>
		</table>
	</tr>
	</tbody>
	</table>
	<?php endif; ?>
<?php endfor ?>
<br><br><br>
<?php endif; ?>