<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$_productMainImg = null;

$link =  "//$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$escaped_link = htmlspecialchars($link, ENT_QUOTES, 'UTF-8');

$breadcrumb = str_replace(".html", "",$escaped_link);
$breadcrumb = str_replace("//www.pursuitbicycles.com", "",$breadcrumb);
$breadcrumb = strtoupper($breadcrumb);

$breadcrumbArray = split("/", $breadcrumb);
array_splice($breadcrumbArray, 0, 1);

$breadcrumbArray[0] = $breadcrumbArray[0] && strrpos($breadcrumbArray[0], "-") === false ? "/ "."<a class='white_red' href='https://www.pursuitbicycles.com/shop.html'>".$breadcrumbArray[0]."</a>" : "";
$breadcrumbArray[1] = $breadcrumbArray[1] && strrpos($breadcrumbArray[1], "-") === false ? " / "."<a class='white_red' href='../".strtolower($breadcrumbArray[1]).".html'>".$breadcrumbArray[1]."</a>" : "";
$breadcrumbArray[2] = $breadcrumbArray[2] && strrpos($breadcrumbArray[2], "-") === false ? " / "."<a class='white_red' href='../".strtolower($breadcrumbArray[2]).".html'>".$breadcrumbArray[2]."</a>" : "";
$nameCrumb = " / ".$_helper->productAttribute($_product, $_product->getName(), 'name');
$breadcrumb = $breadcrumbArray[0].$breadcrumbArray[1].$breadcrumbArray[2].$nameCrumb;
if($breadcrumb == $nameCrumb) {
	$breadcrumb = "/ "."<a class='white_red' href='https://www.pursuitbicycles.com/shop.html'>shop</a>".$nameCrumb;
}
?>
<table class="no_border_table" style="width: 952px;">
<tbody>
<tr>
 <td style="width: 952px; font-size: 12px;">
 <script type="text/javascript">
     var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
 </script>
 <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
 <table style="width: 100%;">
     	<tbody>
     	<tr>
     		<td class="table_header"><span class="table_span" style="font-size: 8pt; top: -14px;">
     		<?php echo $breadcrumb; ?>
     		</span></td>
     	</tr>
     	<tr>
     		<td style="background-color:#000000;">
     			<div style=" width: 760px; float: left;" id="product_images">
     			<ul class="product-images">
					<?php foreach($_product->getMediaGalleryImages() as $image): ?>
						<?php if($_productMainImg == null) {$_productMainImg = $this->helper('catalog/image')->init($_product, 'image', $image->getFile())->resize(760)->setQuality(100); } ?>
						<li style="float: none; list-style: none; position: absolute; width: 760px; z-index: 0; display: none;">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $image->getFile())->resize(760)->setQuality(100); ?>" alt="" />
						</li>
					<?php endforeach; ?>
				</ul>
				</div>
				<div id="bx-pager" style="display: table-caption;">
				<?php $slideIndex=0 ?>
				<?php foreach($_product->getMediaGalleryImages() as $image): ?>
					<a data-slide-index="<?php echo $slideIndex ?>" href=''><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $image->getFile())->resize(190)->setQuality(100); ?>" alt="" /></a>
					<?php $slideIndex++ ?>
				<?php endforeach; ?>
                </div>
     		</td>
     	</tr>
     	<tr>
			<td class="table_description">
			<span style="color: white;font-size: large;font-family: 'Avenir LT W02 95 Black';">
			<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
			</span>
            <br><br>
            <ul class="social-links" style="display: -webkit-box;">
				<li><a class="footer-links pinterest-viral" href="javascript:selectPinImage('', ' - https://www.pursuitbicycles.com', true, document.getElementById('product_images'))" target="_blank"></a></li>
				<li><a class="footer-links facebook-viral" href="javascript:onFaceBookShare('<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>',
				' ',
				'<?php echo $_product->getShortDescription(); ?>',
				'<?php echo $_productMainImg; ?>',
				'<?php echo $_SERVER['HTTP_REFERER'].$_SERVER['REDIRECT_URL'] ?>')" target="_blank"></a></li>
				<li><a class="footer-links twitter-viral" href="javascript:onTwitterShare('<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>',
				'<?php echo $_SERVER['HTTP_REFERER'].$_SERVER['REDIRECT_URL'] ?>')"></a></li>
			</ul>
			<br>
			<div class="product-essential">
                      <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                          <?php echo $this->getBlockHtml('formkey') ?>
                          <div class="no-display">
                              <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                              <input type="hidden" name="related_product" id="related-products-field" value="" />
                          </div>

                          <div class="product-shop">
							  <?php echo $this->getChildHtml('alert_urls') ?>
							  <?php echo $this->getChildHtml('product_type_data') ?>
							  <?php echo $this->getTierPriceHtml() ?>
							  <?php echo $this->getChildHtml('extrahint') ?>

                              <?php if (!$this->hasOptions()):?>
                                  <div class="add-to-box">
                                      <?php if($_product->isSaleable()): ?>
                                          <?php echo $this->getChildHtml('addtocart') ?>
                                          <?php /*$this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) */ if(false): ?>
                                              <span class="or"><?php echo $this->__('OR') ?></span>
                                          <?php endif; ?>
                                      <?php endif; ?>
                                      <?php echo $this->getChildHtml('addto') ?>
                                  </div>
                                  <?php echo $this->getChildHtml('extra_buttons') ?>
                              <?php elseif (!$_product->isSaleable()): ?>
                                  <div class="add-to-box">
                                      <?php echo $this->getChildHtml('addto') ?>
                                  </div>
                              <?php endif; ?>
                              <?php echo $this->getChildHtml('other');?>

                              <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                                  <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                              <?php endif;?>

                          </div>

                          <div class="clearer"></div>
                          <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                              <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                          <?php endif;?>
                      </form>
                      <script type="text/javascript">
                      //<![CDATA[
                          var productAddToCartForm = new VarienForm('product_addtocart_form');
                          productAddToCartForm.submit = function(button, url) {
                              if (this.validator.validate()) {
                                  var form = this.form;
                                  var oldUrl = form.action;

                                  if (url) {
                                     form.action = url;
                                  }
                                  var e = null;
                                  try {
                                      this.form.submit();
                                  } catch (e) {
                                  }
                                  this.form.action = oldUrl;
                                  if (e) {
                                      throw e;
                                  }

                                  if (button && button != 'undefined') {
                                      button.disabled = true;
                                  }
                              }
                          }.bind(productAddToCartForm);

                          productAddToCartForm.submitLight = function(button, url){
                              if(this.validator) {
                                  var nv = Validation.methods;
                                  delete Validation.methods['required-entry'];
                                  delete Validation.methods['validate-one-required'];
                                  delete Validation.methods['validate-one-required-by-name'];
                                  // Remove custom datetime validators
                                  for (var methodName in Validation.methods) {
                                      if (methodName.match(/^validate-datetime-.*/i)) {
                                          delete Validation.methods[methodName];
                                      }
                                  }

                                  if (this.validator.validate()) {
                                      if (url) {
                                          this.form.action = url;
                                      }
                                      this.form.submit();
                                  }
                                  Object.extend(Validation.methods, nv);
                              }
                          }.bind(productAddToCartForm);
                      //]]>
                      </script>
                <br>
				<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
				   <div class="box-collateral <?php echo "box-{$alias}"?>">
					   <?php if ($title = $this->getChildData($alias, 'title')):?>
					   <h2><?php echo $this->escapeHtml($title); ?></h2>
					   <?php endif;?>
					   <?php echo $html; ?>
				   </div>
				<?php endforeach;?>
			</div>
			</td>
		</tr>
     	</tbody>
     </table>
     <div class="block-related-wrapper">
     <?php echo $this->getLayout()->createBlock('catalog/product_list_related')->setTemplate('catalog/product/list/related.phtml')->toHtml() ?>
     </div>
     <div class="block-viewed-wrapper">
     <?php echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/product_viewed.phtml')->toHtml(); ?>
     </div>
     <br>
</tr>
</tbody>
</table>