<table class="no_border_table" style="width: 952px; background-color: black;" cellspacing="0" cellpadding="0">
<tbody>
</tbody>
</table>
<table class="no_border_table" style="width: 900px;">
<tbody>
<tr>
<td style="width: 20%; height: 155px; font-family:'Avenir LT W02 65 Medium'">
<p><span style="font-size: medium;"><strong><br /></strong></span></p>
<p><span style="font-size: medium;"><strong>PURSUIT BICYCLES</strong></span></p>
<p>734 San Pablo Avenue<br />Albany California 94706</p>
<p>510.900.1144</p>
<p>PursuitBicycles@gmail.com</p>
</td>
<td rowspan="6" bgcolor="#000000"><!--nothing--></td>
<td style="width: 80%; padding-left: 30px; font-size: 12px;" rowspan="5">
<p>&nbsp;</p>
<p>Our Mission<br /> We are passionate about the bicycle in all its forms. Our mission statement is simple: We don&rsquo;t just sell bicycles, parts, and accessories. We sell the tools for a lifetime of cycling &ndash; an Infinite Cycle.</p>
<p>Although Infinite Cycles is relatively new to the neighborhood it was founded by people who have grown up in bicycle shops here in Utah and across the country. Bicycles are our life. We have come to the conclusion that there is the perfect bicycle out there for everyone&hellip; some just need a little help finding it.</p>
<p>Our commitment is to help you find whatever you are looking for. No question is too basic or advanced. Everyone is welcome. Let&rsquo;s ride!</p>
<p>&nbsp;</p>
<p>Our History</p>
<p>Infinite Cycles began as a university business plan competition entry. It did well in the competition, so work continued until the doors opened for business. Infinite Cycles opened their first store in Riverton in May 2007. Since we opened, people have been excited to see a new bike shop on the southwest corner of the valley. We quickly outgrew our small shop and more than doubled our size with an expansion in November 2009. By having more and more bikes available on the showroom floor we could help more people find the right bike. Our Riverton store has undergone many remodeling projects in the five years we&rsquo;ve been there and anticipate more to come.</p>
<p>In the summer of 2011 the Highland/Lehi location had an eventful grand opening with the Liquigas-Cannondale pro cycling team after the Tour of Utah. Coming into an area with so many committed and experienced cyclists has been fun. We look forward to continue to bring more of the products and services you need in the future. One of our favorite things we do is getting involved with the community in events and rides. As much fun as it is in the bike shop, we like getting out on the road and trails with you.</p><br><br>
</td>
</tr>
<tr>
<td bgcolor="#000000" height="1"><!--nothing--></td>
</tr>
<tr>
<td style="height: 90px; font-family:'Avenir LT W02 65 Medium'">
<p><strong><br /></strong></p>
<p>Hours of Operation<br />MON-SUN 11am - 7pm<br />Closed on TUES</p>
</td>
</tr>
<tr>
<td bgcolor="#000000" height="1"><!--nothing--></td>
</tr>
<tr>
<td><p>&nbsp;</p>
  <p><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?></p></td>
</tr>
<tr>
<td>&nbsp;</td>
<td style="width: 80%; padding-left: 30px; font-size: 12px; text-align: right; height: 215px">&nbsp;<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/uploaded_images/signature.png" alt="Signature" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</td>
</tr>
</tbody>
</table>