<table class="table_info" style="border: none">
	<tbody>
	<tr>
		<td class="table_header"><span class="table_span">Pursuit Builds</span></td>
	</tr>
	<tr>
		<td>
			<ul id="slider1">
				<li>
				<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('custom/pursuitbuilds1.phtml')->toHtml(); ?>
				</li>
				<li>
				<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('custom/pursuitbuilds2.phtml')->toHtml(); ?>
				</li>
				<li>
				<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('custom/pursuitbuilds3.phtml')->toHtml(); ?>
				</li>
			</ul>
		</td>
	</tr>
	</tbody>
</table>
<br>
<br>