<table class="table_info" style="border: 0px; margin-top: 20px;">
	<tbody>
	<tr>
		<td colspan="3" class="table_header"><span class="table_span">Shop Now</span></td>
	</tr>
	<tr>
		<td style="overflow:hidden;" width="317" height="285"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shop_now_1a')->toHtml(); ?></td>
		<td style="overflow:hidden;" width="317" height="460" rowspan="2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shop_now_2')->toHtml(); ?></td>
		<td style="overflow:hidden;" width="317" height="285"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shop_now_3a')->toHtml(); ?></td>
	</tr>
	<tr>
	  <td style="overflow:hidden;" width="317" height="175"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shop_now_1b')->toHtml(); ?></td>
	  <td style="overflow:hidden;" width="317" height="175"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shop_now_3b')->toHtml(); ?></td>
	</tr>
	</tbody>
</table>