<table class="table_info" style="border: none;  margin-top: 0px;">
	<tbody>
	<tr>
		<td>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pursuitbuilds3_link1')->toHtml(); ?>
		</td>
		<td>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pursuitbuilds3_link2')->toHtml(); ?>
		</td>
		<td>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pursuitbuilds3_link3')->toHtml(); ?>
		</td>
	</tr>
	</tbody>
</table>