<div class="hidden" id="shop-by-style">
	<script type="text/javascript">
		<!--//--><![CDATA[//><!--
			var images = new Array()
			function preload() {
				for (i = 0; i < preload.arguments.length; i++) {
					images[i] = new Image()
					images[i].src = preload.arguments[i]
				}
			}
			preload(
				"../skin/frontend/default/pursuit/images/shop/shop_by_style1A.jpg",
				"../skin/frontend/default/pursuit/images/shop/shop_by_style2A.jpg",
				"../skin/frontend/default/pursuit/images/shop/shop_by_style3A.jpg",
				"../skin/frontend/default/pursuit/images/shop/shop_by_style4A.jpg"
			)
		//--><!]]>
	</script>
</div>
<table class="table_info">
	<tbody>
	<tr>
		<td class="table_header"><span class="table_span">Shop by Style</span></td>
	</tr>
	<tr>
		<td>
		<a class="style road" href="https://www.pursuitbicycles.com/catalogsearch/result/?q=road">ROAD</a>
		<a class="style track" href="https://www.pursuitbicycles.com/catalogsearch/result/?q=track">TRACK</a>
		<a class="style classic" href="https://www.pursuitbicycles.com/catalogsearch/result/?q=classic">CLASSIC</a>
		<a class="style modern" href="https://www.pursuitbicycles.com/catalogsearch/result/?q=modern">MODERN</a>
		<a class="style njs" href="https://www.pursuitbicycles.com/catalogsearch/result/?q=njs">NJS</a>
		</td>
	</tr>
	</tbody>
</table>