<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
	<div class="post-list" style="text-align: -webkit-center;">
		<ul id="post-list" class="post-list-ul">
			<?php foreach($posts as $post): ?>
				<li>
					<?php echo $this->getPostRenderer($post)->toHtml() ?>
				</li>
			<?php endforeach; ?>
		</ul>
		<?php $post = $this->getPost() ?>
		<table class="no_border_table" style="width:952px;" cellpadding="0" cellspacing="0">
		  <tbody>
		<tr>
		<td class="table_header"><span class="table_span">Blog</td>
		</tr>
		  </tbody>
		</table>
		<table width="952" border="0" cellpadding="0" cellspacing="0">
			<tbody style="background: black;">
			<?php $cp=0; ?>
			<?php foreach($posts as $post): ?>
				<?php if( $cp <= 1000 ): ?>
					<?php $cpmodulo = $cp % 3; ?>
					<?php if($cpmodulo==0){ echo "<tr>"; }; ?>
					<td id="post_<?php echo $cp; ?>"><?php echo $this->getPostRendererBlocks($post)->toHtml() ?></td>
					<?php if($cpmodulo==2){ echo "</tr>"; }; ?>
					<?php $cp++; ?>
				<?php endif; ?>
			<?php endforeach; ?>
			<?php if(count($posts)==2 || count($posts)==5 || count($posts)==8){ echo "<td style=\"width: 317px; display: -webkit-box;\">&nbsp;</td>"; }; ?>
			</tbody>
		</table>
		<?php echo $this->getPagerHtml() ?>
	</div>
<?php endif; ?>